dependency issue in some modules
senbox-org/s2tbx pull request #78
Opened 2021-02-10 15:20 UTC by marpet

Dependencies to snap should use snap.version variable in the pom and not project.version. Using project.version causes wrong version of SNAP to be included. Here 8.0.2-SNAPSHOT, but actually it should be 8.0.4-SNAPSHOT.
I've corrected this for two modules.
Can you check the other modules if there is the same issue, please?
Please migrate the changes also to the master.

2021-02-11 08:24 UTC, oanahogoiu approved these changes

2021-02-11 16:42 UTC, Florian1209 commented
There is one on snap-reader-test.
Should I modify also with snap.version?

2021-02-12 07:06 UTC, marpet commented
Do you mean the snap-reader-tests project?
There the versions are already defined explicitly:
https://github.com/senbox-org/snap-reader-tests/blob/98977126d04232e431efbf9fd93a8228acb89387/pom.xml#L21
I think this is okay.

2021-02-12 07:43 UTC, Florian1209 commented
@marpet, You showed me the link of version 9. In this version, there is still some packages org.esa.snap with "project.version"
https://github.com/senbox-org/snap-reader-tests/blob/98977126d04232e431efbf9fd93a8228acb89387/pom.xml#L219
Maybe I'm wrong.

In addition, I mean the snap-reader-tests project on 8.x.
Some org.esa.snap modules like snap-jp2-reader is attached to project version.
https://github.com/senbox-org/snap-reader-tests/blob/af04d7415e29869f2d1d54f81134cbeaa40bdb3a/pom.xml#L200
Can you confirm if the snap-reader-tests project on 8.x should be modified ?

Thanks

2021-02-12 08:47 UTC, marpet commented
You are right. This should also be corrected. The properties snap.version or, if necessary, snap.test.version should be used.

Would be great if you could fix this too.
Thanks.

2021-02-12 09:16 UTC, fdouziech requested changes
@oanahogoiu I have update for all pom.xml. 
Could you please check the new changes?

2021-02-12 13:35 UTC, oanahogoiu commented
@fdouziech  The changes seem OK.
The lib-openjeg and snap-jp2-reader were moved from s2tbx into snap-engine before the 8.0 release, on the master branch, were everything had the same version. That's why these differences in version were not noticed ...

2021-02-12 13:46 UTC, Florian1209 approved these changes

2021-02-12 15:27 UTC, fdouziech approved these changes

2021-02-12 15:31 UTC, merged